ai:
  chat_interface: AI OFF
  translate_interface: Translate OFF
  voice_interface: Print text
lang:
  file: en.yml
  locale: ru
pytorch_proc: cpu
user:
  input_interface: Keybord Input
  translate_interface: Translate OFF
